spring:
#  datasource:
#    url: jdbc:mysql://192.168.9.24:3306/SpringGateway?verifyServerCertificate=false&useSSL=false&requireSSL=false
#    username : root
#    password: p@ssw0rd
#    driver-class-name: com.mysql.jdbc.Driver

  profiles:
    active: dev


mybatis:
  config-location: classpath:mybatis-config.xml
logging:
  level:
    root :  info
    com.mybatis.mapper : trace

server:
  port: 8000



